name: ruta_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  percent_indicator: ^4.2.4
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.3
  sqflite: ^2.0.2
  animated_button: ^0.2.0
  url_launcher: ^6.3.0
  path: ^1.8.0
  animated_text_kit: ^4.2.2
  flutter_charts: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter_Bold.ttf
         - asset: assets/fonts/Inter_ExtraLight.ttf